version: 2.1

default_steps: &default_steps
  steps:
    - checkout
    - run: npm ci
    - run: npm test

jobs:
  tests:
    docker:
      - image: circleci/node:12-browsers
    environment:
      PERCY_ENABLE: 0
    <<: *default_steps
  tests_with_percy:
    # We've opted this node version to be the one that runs and reports Percy's status
    docker:
      - image: circleci/node:10-browsers
    <<: *default_steps

workflows:
  version: 2
  test:
    jobs:
      - tests
      - tests_with_percy